 #in ansible variables can be declared  at multiple levels
 #In ansible variables can be accessed with {{ }} and ${}
 - name: Play level variables
   hosts: all
   vars:
     url: play.example.com
   tasks:
     - name: Print url
       ansible.builtin.debug:
         msg: "url - {{ url }}"

 - name: Task level variables
   hosts: localhost
   connection: local
   tasks:
     - name: Print url
       ansible.builtin.debug:
         msg: "url - {{ url }}"
       vars:
         url: play.example.com

