 #in ansible variables can be declared  at multiple levels
 #In ansible variables can be accessed with {{ }} and ${}
 - name : play level variables
   hosts : localhost
   connections: local
   vars :
   url  : play.example.com
   tasks :
    -name : print url
    ansible.builtin.debug :
     msg : url - {{ url }}

